language: python
python:
  - "3.5"
cache:
  - pip
addons:
  apt:
    packages:
      - nodejs
      - npm
install:
  - pip install flake8
  - npm install eslint
script:
  - cd javascript && eslint .
  - cd core && flake8 --exclude=env --max-line-length=120 --ignore=F401,E402 core
