language: python
python:
  - "3.5"
cache:
  - pip
install:
  - pip install flake8
before_script:
  - export PATH=$(npm bin):$PATH
script:
  - flake8 --exclude=env --max-line-length=120 --ignore=F401,E402 core
