language: python
cache:
  - pip
node_js:
  - "5"
before_script:
  - pip3 install flake8
  - apt-get install nodejs npm
  - npm install -g eslint
script:
  - cd javascript && eslint .
  - cd core && flake8 --exclude=env --max-line-length=120 --ignore=F401,E402 core
