language: python
python:
  - "3.5"
cache:
  - pip
install:
  - pip install flake8
  - apt-get install nodejs npm
  - npm install -g eslint
script:
  - cd javascript && eslint .
  - cd core && flake8 --exclude=env --max-line-length=120 --ignore=F401,E402 core
