version: '2'
services:
  redis:
    build: redis
  core:
    build: core
    links:
      - redis:redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
  nodecmd:
    build: javascript
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
    cap_drop:
      - ALL
  phpcmd:
    build: php
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
    cap_drop:
      - ALL
