version: '2'
services:
  redis:
    image: redis:alpine
  core:
    build: core
    links:
      - redis:redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
  basecommands:
    build: basecommands
    links:
      - redis:redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
  watcher:
    build: watcher
    links:
      - redis:redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
  watcher_backend:
    build: watcher
    links:
      - redis:redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
    command: "python3 watcher/tasks.py"
  phpcmd:
    build: php
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
    cap_drop:
      - ALL
